# This is a basic workflow to help you get started with Actions

name: Jest

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      versions:
        description: 'Node versions'
        type: string
        required: false
        default: "[14, 16]"
      manager:
        description: "Package manager"
        type: string
        required: false
        default: "yarn"
      key:
        description: "Private key"
        type: string
        required: true
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      versions:
        description: 'Node versions'
        type: string
        required: false
        default: "[14, 16]"
      manager:
        description: "Package manager"
        type: string
        required: false
        default: "yarn"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ['self-hosted', 'node']
    strategy:
      matrix:
        node: ${{ fromJSON(inputs.versions) }}
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: 'Ssh agent'
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ inputs.key }}
    - if: ${{ inputs.manager == 'pnpm' }}
      name: Use package manager
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(inputs.manager == 'pnpm' && '**/pnpm-lock.yaml' || '**/yarn.lock') }}
    - name: Install dependencies
      run: ${{ inputs.manager }} install
    - name: Playwright
      run: npx playwright install
    - name: Tests
      run: ${{ inputs.manager }} test
    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
