# This is a basic workflow to help you get started with Actions

name: Jest

# Controls when the workflow will run
on:
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ['self-hosted', 'node']
    strategy:
      matrix:
        node: [14, 16]
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
          persist-credentials: false
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: yarn install
    - name: Playwright
      run: npx playwright install
    - name: Tests
      run: yarn test
    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
