name: Lighthouse

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      site:
        required: true
        type: string
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        site:
          required: true
          type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  performance:
    # The type of runner that the job will run on
    runs-on: ['self-hosted', 'node']
    strategy:
      matrix:
        node: [18]
    steps:
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install lighthouse
        run: npm install -g @unlighthouse/cli puppeteer
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - run: which chrome
      - name: Run lighthouse
        run: export CHROME_PATH=/home/ubuntu/actions-runner/_work/_tool/chromium/latest/x64/chrome && unlighthouse-ci --site ${{ inputs.site }} --reporter jsonExpanded
