# This is a basic workflow to help you get started with Actions

name: prepare

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      node:
        description: 'node version'
        required: true
        type: string
        default: 16
      pnpm:
        description: 'pnpm version'
        required: false
        type: string
        default: 8.9.2
      username:
        description: 'git username'
        required: true
        type: string
      email:
        description: 'git email'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Release step
  prepare:
    runs-on: ['self-hosted', 'chore']
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node }}

      - name: Setup pnpm
        shell: bash
        run: npm install -g pnpm@${{ inputs.pnpm }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Build package
        shell: bash
        run: pnpm unbuild

      - name: Get current branch
        id: current_branch
        run: echo "VERSION=${{ github.event.pull_request && github.head_ref || github.ref_name }}" >> $GITHUB_ENV

      - name: Display version
        run: echo ${{ env.VERSION }}

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Download script
        run: curl -o $PWD/release.cjs https://raw.githubusercontent.com/iomediacommunication/pipeline/main/.github/scripts/release.cjs

      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Give script permissions
        run: chmod +x $PWD/release.cjs

      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Update version
        shell: bash
        run: node $PWD/release.cjs ${{ env.VERSION }}

      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Remove script
        run: rm -rf $PWD/release.cjs

      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Commit and push changes
        continue-on-error: true
        run: |
          git config --global user.name "${{ inputs.username }}"
          git config --global user.email "${{ inputs.email }}"
          git add .
          git commit --no-verify -m "ci(deps): sync packages deps to v${{ env.VERSION }}"
          git push
