# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      tag:
        description: 'tag'
        required: true
        type: string
      prerelease:
        description: 'prerelease'
        required: true
        type: boolean
        default: false
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Release step
  release:
    name: Build release
    runs-on: ['self-hosted', 'node']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
      - name: Update version
        uses: maxgfr/github-change-json@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
        with:
          key: 'version'
          value: '${{ inputs.tag }}'
          path: package.json
          commit: true
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
        with:
          tag_name: 'v${{ inputs.tag }}'
          release_name: 'v${{ inputs.tag }}'
          body: |
            ## Features
            - feat:
            ## Fixes
            - fix:
            ## Chores
            - chore:
          draft: false
          prerelease: ${{ inputs.prerelease }}
