# This is a basic workflow to help you get started with Actions

name: split

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      tag:
        description: 'tag'
        required: false
        type: string
        default: ''
      branch:
        description: 'branch'
        required: false
        type: string
        default: ''
      packages:
        description: 'packages'
        type: string
        required: true
        default: "[]"
      organisation:
        description: 'github organisation'
        required: true
        type: string
      username:
        description: 'git username'
        required: true
        type: string
      email:
        description: 'git email'
        required: true
        type: string
      path:
        description: 'packages path'
        required: false
        type: string
        default: 'packages'

env:
  GITHUB_TOKEN: ${{ secrets.GH_COMPOSER_AUTH }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Split step
  split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(inputs.packages) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current branch
        id: vars
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Ssh agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - if: ${{ inputs.branch != '' }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        with:
          package_directory: ${{ inputs.path }}/${{ matrix.package }}
          repository_organization: ${{ inputs.organisation }}
          repository_name: ${{ matrix.package }}
          user_name: ${{ inputs.username }}
          user_email: ${{ inputs.email }}
          branch: ${{ inputs.branch }}

      - if: ${{ inputs.tag != '' }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        with:
          package_directory: ${{ inputs.path }}/${{ matrix.package }}
          repository_organization: ${{ inputs.organisation }}
          repository_name: ${{ matrix.package }}
          user_name: ${{ inputs.username }}
          user_email: ${{ inputs.email }}
          tag: v${{ inputs.tag }}
          branch: ${{ env.VERSION }}
