# This is a basic workflow to help you get started with Actions

name: template

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      node:
        description: 'node version'
        required: true
        type: string
        default: 16
      pnpm:
        description: 'pnpm version'
        required: false
        type: string
        default: 8.9.2
      path:
        description: 'template path'
        required: true
        type: string
      package:
        description: 'pnpm package'
        required: true
        type: string
      username:
        description: 'git username'
        required: true
        type: string
      email:
        description: 'git email'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Update step
  update:
    runs-on: ['self-hosted', 'chore']
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node }}

      - name: Setup pnpm
        shell: bash
        run: npm install -g pnpm@${{ inputs.pnpm }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current directory
        id: current_directory
        run: echo "CURRENT_DIR=$PWD" >> $GITHUB_ENV

      - name: Change directory
        shell: bash
        run: cd ${{ inputs.path }}

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Update dependencies
        shell: bash
        run: pnpm up "${{ inputs.package }}"

      - name: Change directory
        shell: bash
        run: cd ${{ env.CURRENT_DIR }}

      - name: Get current branch or tag
        id: current_branch
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Display version
        run: echo ${{ env.VERSION }}

      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Commit and push changes
        continue-on-error: true
        run: |
          git config --global user.name "${{ inputs.username }}"
          git config --global user.email "${{ inputs.email }}"
          git add .
          git commit -m "ci: update template ${{ inputs.package }} to ${{ env.VERSION }}"
          git push
