# This is a basic workflow to help you get started with Actions

name: template

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      node:
        description: 'node version'
        required: true
        type: string
        default: 16
      pnpm:
        description: 'pnpm version'
        required: false
        type: string
        default: 8.9.2
      working_directory:
        description: 'template path'
        required: true
        type: string
      package:
        description: 'pnpm package'
        required: true
        type: string
      username:
        description: 'git username'
        required: true
        type: string
      email:
        description: 'git email'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Update step
  update:
    runs-on: ['self-hosted', 'chore']
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node }}

      - name: Setup pnpm
        shell: bash
        run: npm install -g pnpm@${{ inputs.pnpm }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ${{ inputs.working_directory }}
        shell: bash
        run: pnpm --ignore-workspace install --no-frozen-lockfile --config.confirmModulesPurge=false --ignore-scripts

      - name: Update
        working-directory: ${{ inputs.working_directory }}
        shell: bash
        run: pnpm --ignore-workspace --ignore-scripts --latest up "${{ inputs.package }}"

      - name: Update
        working-directory: ${{ inputs.working_directory }}
        shell: bash
        run: pnpm --ignore-workspace --ignore-scripts --latest up "${{ inputs.package }}"

      - name: Get current branch
        id: current_branch
        run: echo "VERSION=${{ github.event.pull_request && github.head_ref || github.ref_name }}" >> $GITHUB_ENV

      - name: Display version
        run: echo ${{ env.VERSION }}

      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Commit and push changes
        continue-on-error: true
        run: |
          git pull
          git config --global user.name "${{ inputs.username }}"
          git config --global user.email "${{ inputs.email }}"
          git add .
          git commit --no-verify -m "ci: pnpm update ${{ env.VERSION }}"
          git push
